parameters:
    fromEmail: 'noreply@shop-training.com'
    shopName: 'ShopTraining'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    app.service.user_service:
        class: App\Service\UserService
        arguments:
            - '@http_client'
            - '%env(CUSTOMER_API_URL)%'
            - '%env(CUSTOMER_API_KEY)%'

    app.service.config_service:
        class: App\Service\ConfigService
        arguments:
            - '%kernel.project_dir%'

    app.service.invoice_service:
        class: App\Service\InvoiceService
        arguments:
            - '@http_client'
            - '%env(BILLING_API_URL)%'
            - '%env(BILLING_API_KEY)%'

    app.service.order_notification_manager:
        class: App\Service\OrderNotificationManager
        arguments:
            - '@twig'
            - '@mailer'
            - '@app.service.user_service'
            - '@app.service.config_service'
            - '@app.service.invoice_service'
            - '%fromEmail%'
            - '%shopName%'

    App\Service\OrderNotificationManager:
        alias: app.service.order_notification_manager

    App\Service\UserService:
        alias: app.service.user_service

    App\Service\InvoiceService:
        alias: app.service.invoice_service
